use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
};

const BUILD_INSTRUCTIONS: &str =
    "build the dashboard before Cargo: cd dashboard && npm ci && npm run verify";

fn main() {
    println!("cargo:rerun-if-changed=../../dashboard/package.json");
    println!("cargo:rerun-if-changed=../../dashboard/package-lock.json");
    println!("cargo:rerun-if-changed=../../dashboard/vite.config.ts");
    println!("cargo:rerun-if-changed=../../dashboard/index.html");
    println!("cargo:rerun-if-changed=../../dashboard/src");
    println!("cargo:rerun-if-changed=../../dashboard/dist");

    if let Err(error) = generate_asset_table() {
        panic!("could not embed the production dashboard: {error}\n{BUILD_INSTRUCTIONS}");
    }
}

fn generate_asset_table() -> Result<(), String> {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "Cargo did not provide CARGO_MANIFEST_DIR".to_owned())?,
    );
    let dashboard_dir = manifest_dir.join("../../dashboard");
    let lockfile = dashboard_dir.join("package-lock.json");
    require_file(&lockfile, "dashboard/package-lock.json")?;

    let dist_dir = dashboard_dir.join("dist");
    let index_path = dist_dir.join("index.html");
    require_file(&index_path, "dashboard/dist/index.html")?;

    let mut files = Vec::new();
    collect_files(&dist_dir, &dist_dir, &mut files)?;
    files.sort_by(|left, right| left.0.cmp(&right.0));
    if files.is_empty() {
        return Err("dashboard/dist contains no production assets".to_owned());
    }

    let asset_paths = files
        .iter()
        .map(|(url_path, _)| url_path.as_str())
        .collect::<BTreeSet<_>>();
    validate_index_references(&index_path, &asset_paths)?;

    let mut generated = String::from(
        "// @generated by crates/sink-client/build.rs from dashboard/dist.\n\
         const PRODUCTION_ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (url_path, relative_path) in files {
        let content_type = content_type(&relative_path)?;
        let include_suffix = format!("/../../dashboard/dist/{relative_path}");
        generated.push_str(&format!(
            "    ({url_path:?}, {content_type:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {include_suffix:?}))),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR").ok_or_else(|| "Cargo did not provide OUT_DIR".to_owned())?,
    );
    fs::write(out_dir.join("dashboard_assets.rs"), generated)
        .map_err(|error| format!("could not write generated asset metadata: {error}"))
}

fn require_file(path: &Path, label: &str) -> Result<(), String> {
    match fs::metadata(path) {
        Ok(metadata) if metadata.is_file() => Ok(()),
        Ok(_) => Err(format!("expected {label} to be a regular file")),
        Err(error) => Err(format!("expected {label}, but it is unavailable: {error}")),
    }
}

fn collect_files(
    root: &Path,
    directory: &Path,
    files: &mut Vec<(String, String)>,
) -> Result<(), String> {
    let mut entries = fs::read_dir(directory)
        .map_err(|error| format!("could not read {}: {error}", directory.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("could not enumerate {}: {error}", directory.display()))?;
    entries.sort_by_key(fs::DirEntry::file_name);

    for entry in entries {
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)
            .map_err(|error| format!("could not inspect {}: {error}", path.display()))?;
        if metadata.file_type().is_symlink() {
            return Err(format!(
                "dashboard/dist must not contain symbolic links: {}",
                path.display()
            ));
        }
        if metadata.is_dir() {
            collect_files(root, &path, files)?;
            continue;
        }
        if !metadata.is_file() {
            return Err(format!(
                "dashboard/dist contains a non-regular asset: {}",
                path.display()
            ));
        }
        if metadata.len() == 0 {
            return Err(format!(
                "dashboard/dist contains an empty asset: {}",
                path.display()
            ));
        }
        let relative = path
            .strip_prefix(root)
            .map_err(|error| format!("could not normalize {}: {error}", path.display()))?;
        let relative = relative
            .iter()
            .map(|component| {
                component
                    .to_str()
                    .ok_or_else(|| format!("dashboard asset path is not UTF-8: {}", path.display()))
            })
            .collect::<Result<Vec<_>, _>>()?
            .join("/");
        files.push((format!("/{relative}"), relative));
    }
    Ok(())
}

fn validate_index_references(index_path: &Path, assets: &BTreeSet<&str>) -> Result<(), String> {
    let index = fs::read_to_string(index_path)
        .map_err(|error| format!("dashboard/dist/index.html is not valid UTF-8: {error}"))?;
    for attribute in ["src=\"", "href=\""] {
        let mut remainder = index.as_str();
        while let Some(start) = remainder.find(attribute) {
            remainder = &remainder[start + attribute.len()..];
            let Some(end) = remainder.find('"') else {
                return Err(format!(
                    "dashboard/dist/index.html has an unterminated {attribute} attribute"
                ));
            };
            let reference = &remainder[..end];
            if reference.starts_with('/') && !assets.contains(reference) {
                return Err(format!(
                    "dashboard/dist/index.html references missing production asset {reference}"
                ));
            }
            remainder = &remainder[end + 1..];
        }
    }
    Ok(())
}

fn content_type(relative_path: &str) -> Result<&'static str, String> {
    let extension = Path::new(relative_path)
        .extension()
        .and_then(|extension| extension.to_str())
        .map(str::to_ascii_lowercase)
        .ok_or_else(|| format!("dashboard asset has no MIME extension: {relative_path}"))?;
    match extension.as_str() {
        "html" => Ok("text/html; charset=utf-8"),
        "css" => Ok("text/css; charset=utf-8"),
        "js" | "mjs" => Ok("application/javascript; charset=utf-8"),
        "json" | "map" | "webmanifest" => Ok("application/json; charset=utf-8"),
        "txt" => Ok("text/plain; charset=utf-8"),
        "xml" => Ok("application/xml"),
        "svg" => Ok("image/svg+xml"),
        "png" => Ok("image/png"),
        "jpg" | "jpeg" => Ok("image/jpeg"),
        "gif" => Ok("image/gif"),
        "webp" => Ok("image/webp"),
        "avif" => Ok("image/avif"),
        "ico" => Ok("image/x-icon"),
        "woff" => Ok("font/woff"),
        "woff2" => Ok("font/woff2"),
        "ttf" => Ok("font/ttf"),
        "otf" => Ok("font/otf"),
        "wasm" => Ok("application/wasm"),
        _ => Err(format!(
            "dashboard asset has no exact MIME mapping: {relative_path}"
        )),
    }
}
